#This docker file will create a docker container for the CommonKmers method

FROM cami/profiling

MAINTAINER David Koslicki version: 0.1

#Install Jellyfish
apt-get -y update
apt-get install -y wget
mkdir jellyfish
cd jellyfish
wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.0/jellyfish-2.2.0.tar.gz
tar -xzf jellyfish-2.2.0.tar.gz
cd jellyfish-2.2.0
apt-get install -y g++
./configure
apt-get install -y build-essentials
make
cd ..

#Install Julia
apt-get install -y software-properties-common python-software-properties
add-apt-repository ppa:staticfloat/juliareleases
add-apt-repository ppa:staticfloat/julia-deps
apt-get -y update
apt-get install -y hdf5-tools

#Install Julia packages
julia -e 'Pkg.add("HDF5"); Pkg.add("ArgParse");'

#Get the CommonKmers code
apt-get install -y git
git clone https://github.com/dkoslicki/CommonKmers.git

#Install query per sequence
cd CommonKmers
cd src
cd QueryPerSeq
g++ -I /jellyfish/jellyfish-2.2.0/include -std=c++0x -Wall -O3 -L /jellyfish/jellyfish-2.2.0/.libs -l jellyfish-2.0 -l pthread -Wl,--rpath=/jellyfish/jellyfish-2.2.0/.libs query_per_sequence.cc sequence_mers.hpp -o query_per_sequence
cp query_per_sequence /usr/local/bin
cd

#Install gunzip
apt-get install -y gunzip

#Set data directory
ENV CONT_DATABASES_DIR


#Create tasks
#Pull these from github



#Install CommonKmers database
echo "Be sure to download the training data at http://www.math.oregonstate.edu/~koslickd/CommonKmersData.tar.gz and uncompress it. The resulting directory should be passed to docker at the location CONT_DATABASES_DIR via: \'-v /path/to/uncompressed/Data:/dckr/mnt/camiref/CommonKmersData:ro\'"